### PR TITLE
AUC calculations

### PR DESCRIPTION
**Pull request by mortonjt**

### CODE REVIEW

**Comment by ehthiede** [comment]
Hi Jamie,

Code looks great :-).  One quick question though: I think right now train_bpr.py doesn't have run_model_on_batch defined.  Is that correct, and if so could I ask you to tweak that?  Thanks :-)

**Comment by mortonjt** [comment]
@ehthiede of course!

**Comment by ehthiede** [comment]
Awesome, merged!

**Comment by mortonjt** [comment]
Thanks! I'll push in the fixes to BPR in a bit.

Sorry about the confusion on the last message

**Pull request merged**
